export const notificationMessages = {
  en: { title: 'Notifications', unread: 'unread', all: 'All', unreadOnly: 'Unread', markAll: 'Mark all read', markRead: 'Mark read', critical: 'Critical', warning: 'Warning', info: 'Information', empty: 'You’re all caught up', emptyBody: 'There are no notifications to show here.', loading: 'Loading notifications…', error: 'Could not load notifications.', retry: 'Try again', saving: 'Saving…', saveError: 'Could not mark notifications read. Try again.', demo: 'Demo notifications · sample data', back: 'Back to workspace' },
  si: { title: 'දැනුම්දීම්', unread: 'නොකියවූ', all: 'සියල්ල', unreadOnly: 'නොකියවූ', markAll: 'සියල්ල කියවූ ලෙස සලකුණු කරන්න', markRead: 'කියවූ ලෙස සලකුණු කරන්න', critical: 'හදිසි', warning: 'අවවාදය', info: 'තොරතුරු', empty: 'සියල්ල කියවා ඇත', emptyBody: 'පෙන්වීමට දැනුම්දීම් නැත.', loading: 'දැනුම්දීම් පූරණය වෙමින්…', error: 'දැනුම්දීම් පූරණය කළ නොහැක.', retry: 'නැවත උත්සාහ කරන්න', saving: 'සුරකිමින්…', saveError: 'සලකුණු කළ නොහැක. නැවත උත්සාහ කරන්න.', demo: 'ආදර්ශ දැනුම්දීම් · නියැදි දත්ත', back: 'වැඩබිමට ආපසු' },
  ta: { title: 'அறிவிப்புகள்', unread: 'படிக்காதவை', all: 'அனைத்தும்', unreadOnly: 'படிக்காதவை', markAll: 'அனைத்தையும் படித்ததாகக் குறி', markRead: 'படித்ததாகக் குறி', critical: 'அவசரம்', warning: 'எச்சரிக்கை', info: 'தகவல்', empty: 'அனைத்தையும் படித்துவிட்டீர்கள்', emptyBody: 'காட்ட அறிவிப்புகள் இல்லை.', loading: 'அறிவிப்புகள் ஏற்றப்படுகின்றன…', error: 'அறிவிப்புகளை ஏற்ற முடியவில்லை.', retry: 'மீண்டும் முயலவும்', saving: 'சேமிக்கிறது…', saveError: 'படித்ததாகக் குறிக்க முடியவில்லை. மீண்டும் முயலவும்.', demo: 'மாதிரி அறிவிப்புகள் · மாதிரித் தரவு', back: 'பணியிடத்திற்குத் திரும்பு' },
}

export const layoutMessages = {
  en: { home: 'Home', orders: 'Orders', deliveries: 'Deliveries', issues: 'Issues', settings: 'Settings', more: 'More', needsAction: 'Needs action', today: 'Today', yesterday: 'Yesterday', earlier: 'Earlier', new: 'new', receipt: 'Confirm receipt', close: 'Close', details: 'Notification details', unavailable: 'This is a demo notification. The delivery and issue workflows will be connected when those features are ready.', demo: 'Demo workspace', coming: 'Not available yet', critical: 'Critical · act now', markHint: 'Open details and mark read', live: 'Dispatch workspace' },
  si: { home: 'මුල් පිටුව', orders: 'ඇණවුම්', deliveries: 'බෙදාහැරීම්', issues: 'ගැටලු', settings: 'සැකසුම්', more: 'තවත්', needsAction: 'ක්‍රියාමාර්ග අවශ්‍යයි', today: 'අද', yesterday: 'ඊයේ', earlier: 'පෙර', new: 'නව', receipt: 'ලැබීම තහවුරු කරන්න', close: 'වසන්න', details: 'දැනුම්දීමේ විස්තර', unavailable: 'මෙය ආදර්ශ දැනුම්දීමකි. අදාළ විශේෂාංග සූදානම් වූ විට බෙදාහැරීම් සහ ගැටලු කාර්යයන් සම්බන්ධ කෙරේ.', demo: 'ආදර්ශ වැඩබිම', coming: 'තවම නොමැත', critical: 'හදිසි · දැන් ක්‍රියා කරන්න', markHint: 'විස්තර විවෘත කර කියවූ ලෙස සලකුණු කරන්න', live: 'බෙදාහැරීම් වැඩබිම' },
  ta: { home: 'முகப்பு', orders: 'ஆர்டர்கள்', deliveries: 'விநியோகங்கள்', issues: 'சிக்கல்கள்', settings: 'அமைப்புகள்', more: 'மேலும்', needsAction: 'செயல் தேவை', today: 'இன்று', yesterday: 'நேற்று', earlier: 'முன்பு', new: 'புதியவை', receipt: 'பெற்றதை உறுதிசெய்', close: 'மூடு', details: 'அறிவிப்பு விவரங்கள்', unavailable: 'இது மாதிரி அறிவிப்பு. தொடர்புடைய அம்சங்கள் தயாரானதும் விநியோக மற்றும் சிக்கல் செயல்பாடுகள் இணைக்கப்படும்.', demo: 'மாதிரிப் பணியிடம்', coming: 'இன்னும் கிடைக்கவில்லை', critical: 'அவசரம் · உடனே செயல்படு', markHint: 'விவரங்களைத் திறந்து படித்ததாகக் குறி', live: 'விநியோகப் பணியிடம்' },
}
