import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { storeApi, type Issue } from '../../store/api'
import { Button, Card, Feedback, Heading, Loading } from '../../store/StoreShared'
import { IssuePhoto, IssueStatus } from '../../store/StoreIssues'

export function DispatchIssues() {
  const client = useQueryClient()
  const [status, setStatus] = useState('')
  const [selected, setSelected] = useState<Issue | null>(null)
  const [reply, setReply] = useState('')
  const query = useQuery({ queryKey: ['dispatch', 'issues', status], queryFn: () => storeApi.dispatchIssues(status || undefined), refetchInterval: 15_000, refetchOnWindowFocus: 'always' })
  const send = useMutation({ mutationFn: async (action: 'reply' | 'resolve') => { if (!selected) throw Error('Choose an issue.'); return action === 'reply' ? storeApi.dispatchReply(selected.id, reply) : storeApi.dispatchResolve(selected.id) }, onSuccess: async issue => { setSelected(issue); setReply(''); await client.invalidateQueries({ queryKey: ['dispatch', 'issues'] }) } })
  return <><Heading title="Store issues" subtitle="Reply and resolve from one inbox" /><Feedback error={send.error} /><div className="mb-4 flex gap-2">{['','OPEN','ANSWERED','RESOLVED'].map(x => <button key={x} onClick={() => setStatus(x)} className={`min-h-12 rounded-full px-4 text-sm ${status === x ? 'bg-brand text-on-brand' : 'border border-line bg-surface'}`}>{x || 'All'}</button>)}</div>{!query.data ? <Loading error={query.error} retry={() => void query.refetch()} /> : <div className="grid gap-4 lg:grid-cols-2"><div className="space-y-3">{query.data.items.map(issue => <button key={issue.id} onClick={() => setSelected(issue)} className="w-full rounded-xl border border-line bg-surface p-4 text-left"><div className="flex justify-between gap-2"><strong>{issue.ref}</strong><IssueStatus status={issue.status} /></div><p className="mt-1 text-sm text-muted">{issue.outletId} · {issue.type.toLowerCase()}</p></button>)}</div>{selected && <Card><h2 className="text-xl font-bold">{selected.ref} · {selected.outletId}</h2><p className="mt-2 text-muted">{selected.type.toLowerCase()} · {selected.units ?? '—'} cases · wants {selected.wants.toLowerCase()}</p><div className="mt-5 space-y-3">{selected.messages.map(m => <p key={m.id} className="rounded-lg bg-canvas p-3"><small className="block text-muted">{m.authorName} · {new Date(m.createdAt).toLocaleString()}</small>{m.text}</p>)}</div>{selected.photoIds.length > 0 && <div className="mt-3 flex flex-wrap gap-3">{selected.photoIds.map(photoId => <IssuePhoto key={photoId} issueId={selected.id} photoId={photoId} dispatch />)}</div>}{selected.status !== 'RESOLVED' && <><textarea value={reply} onChange={e => setReply(e.target.value)} placeholder="Reply to store" className="mt-5 min-h-24 w-full rounded-lg border border-line p-3" /><div className="mt-3 flex flex-wrap gap-3"><Button disabled={!reply.trim() || send.isPending} onClick={() => send.mutate('reply')}>Send reply</Button><Button disabled={send.isPending} tone="secondary" onClick={() => send.mutate('resolve')}>Resolve issue</Button></div></>}</Card>}</div>}</>
}
