spring.application.name=waypoint

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/waypoint}
spring.datasource.username=${DB_USER:waypoint}
spring.datasource.password=${DB_PASSWORD:waypoint}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true
server.port=8080
