import { useState } from 'react'
import { useMutation, useQueryClient } from '@tanstack/react-query'
import { Link } from 'react-router-dom'
import { storeApi, type Order, type OrderEvent } from './api'
import { storeWindowLabel } from './storeLive'
import { Feedback } from './StoreShared'
import './phone-order-check.css'

export function PhoneOrderCheck({ order, history, windowOpen, windowClose }: { order: Order; history: OrderEvent[]; windowOpen?: string; windowClose?: string }) {
  const client = useQueryClient()
  const [dialog, setDialog] = useState(false)
  const [reason, setReason] = useState('Wrong quantity')
  const [correctUnits, setCorrectUnits] = useState(order.units)
  const [message, setMessage] = useState('')
  const [success, setSuccess] = useState('')
  const mutation = useMutation({ mutationFn: (ok: boolean) => storeApi.check(order.id, ok, ok ? undefined : `${reason}${reason === 'Wrong quantity' ? `: correct quantity ${correctUnits} cases` : ''}${message.trim() ? `. ${message.trim()}` : ''}`), onSuccess: async (_, ok) => { setDialog(false); setSuccess(ok ? 'You confirmed this phone order.' : 'Your correction was sent to dispatch.'); await client.invalidateQueries({ queryKey: ['store'] }) } })
  const runDate = new Date(`${order.runDate}T12:00:00`).toLocaleDateString('en-GB', { weekday: 'short', day: 'numeric', month: 'short' })
  return <div className="phone-order-page"><Link to="/store/orders" className="phone-order-back">← Orders</Link><div className="phone-order-banner"><strong>ⓘ Dispatch entered this order for you</strong><span>Please check the details from your call and tell dispatch if something is wrong.</span></div><Feedback error={mutation.error} success={success} /><div className="phone-order-columns"><section className="phone-order-card"><h2>Order details</h2><dl><dt>Line</dt><dd>Fresh {order.temp === 'CHILLED' ? 'chilled' : 'dry'}</dd><dt>Quantity</dt><dd>{order.units} cases</dd><dt>Delivery</dt><dd>{runDate}{windowOpen && windowClose ? ` · ${storeWindowLabel(windowOpen, windowClose)} window` : ''}</dd><dt>Source</dt><dd>Entered by dispatch</dd></dl>{!order.storeChecked ? <div className="phone-order-actions"><button className="phone-primary" disabled={mutation.isPending} onClick={() => mutation.mutate(true)}>⊙ Yes, this is right</button><button disabled={mutation.isPending} onClick={() => setDialog(true)}>Something’s wrong — tell dispatch</button></div> : <p className="phone-order-reviewed">⊙ Your response has been recorded.</p>}</section><section className="phone-order-card"><h2>History</h2>{history.length ? <ol>{history.map((event, index) => <li key={`${event.at}-${index}`}><time>{new Date(event.at).toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' })}</time><span>{event.type.replaceAll('_', ' ').toLowerCase()}</span></li>)}</ol> : <p>No history recorded yet.</p>}</section></div>{dialog && <div className="review-dialog-backdrop"><div className="review-dialog" role="dialog" aria-modal="true" aria-labelledby="phone-dialog-title"><h2 id="phone-dialog-title">What’s wrong with this order?</h2><div className="new-order-reasons">{['Wrong quantity', 'Wrong line', 'Wrong day', 'Other'].map(value => <button type="button" key={value} className={reason === value ? 'selected' : ''} onClick={() => setReason(value)}>{value}</button>)}</div>{reason === 'Wrong quantity' && <label>Correct quantity<input type="number" min="1" step="1" value={correctUnits} onChange={event => setCorrectUnits(Number(event.target.value))} /></label>}<label>Message for dispatch<textarea maxLength={800} value={message} onChange={event => setMessage(event.target.value)} placeholder="Tell dispatch what should change" /></label><div className="review-dialog-actions"><button className="review-confirm" disabled={mutation.isPending || (reason === 'Wrong quantity' && (!Number.isInteger(correctUnits) || correctUnits < 1)) || (reason !== 'Wrong quantity' && !message.trim())} onClick={() => mutation.mutate(false)}>Send to dispatch</button><button onClick={() => setDialog(false)}>Cancel</button></div></div></div>}</div>
}
